name: .NET Core unit testing

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macOS-latest, ubuntu-latest ]
        dotnet: [ 3.1.101 ]

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Run MSTest
      run: dotnet test --configuration Release
