name: .NET Core unit testing

on: [push]

jobs:
  test:
    name: Build & Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macOS-latest, ubuntu-latest ]
        dotnet: [ '3.1.100' ]
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      NUGET_XMLDOC_MODE: skip

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Build
      run: dotnet build --configuration Release
    - name: MSTest
      run: dotnet test --configuration Release --no-build
